appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nMWEPZ3rzlXuiqsorNeF5Io6B2ZT1D3GseqI1O8l5ERod+JvcO8YAHRy95NXcaga9WrjYHFG3FcCDLCqTRxcJcLFk5/48bC+U80NG5ac49HxumGUsAX4x+Q2+LpNvqLtz+FVAw0WdTkzejCi1sDUtov/KqeUAY/GKw7wzUU73qgFZn44ztBc9DJE2JdSEhm3WAzr+N2av2+x/hqzVCRPER4DmCemY2pNpRUyz7JwX4aYaNj22M0ZKjciG2LmawlmhnzLaQaEPF6FZNj9FS7B/YKsmaorevpkU+4knETIX+naO6v4XOOrfOfNeP/9h3EHNdhnFHDjkU8vrweSdpD9+gxNGVG8VpXirghZjZXq0D1IMHrOHAp1OO0D9AMri9U/oQdpZf3HF/7KCMaNpEK0r8r5IYv6Qvwq7vx0BqL4lKCECdIQWKRDNctU2Xfsh/6bfxjO2xFqNGzX8YZqQA6PMQW8g0NXCakZs/8pwwp046RFkap9CYT1pXnkq9D8Ahf1erceH9+AIGlXlItLYzVhQMfTiTlCRnXrQr8zAOvkeW1wTT9vRuXleBtl4eyZbnx1OrnEvD64uyW9frKI3YmWKRmV3BYu347cFLcXPJLLL0gtrquojN425VG9M2+l1HZRw7MpomfvKugQstiEPo3PdwsVfAcxJPAS37tBCl13kaY=}
