travis:
  secure:
    BINSTAR_TOKEN: EcoFpof9QFuiqZJhq5/krDji9MUz7D+Tqb+CFpsnBPHw6L8nq+xqfFJj82ZXG5Ox33pyVjhc2frFCzwk4IzODF682WQqOyHqG1Q4uvIRfFkqSPNv2/bCbi4Z5xaUQhMu/Nf1UEEjAidjskJseo3b38MpDsiIMQg+kxcJCSjeUAGYFS8t2vNlVTxR8dNSqgFa8e+x2ETi+bEtEXqdgYGkJvKwIwgjgV/AaJ42FV9jq41IYYoIOceZyZQJk/AxpuE3/3MWYZcDxPkeZPNwQW7FlZWI1xgLk1PkSXk0//tEQhXJtyLg+hfkvDD3DFQmqb5rQIghoPL19UxfnCw+7ru3C+qWMeUYIx2OGnUIcfqHX36qKiwRngltYyMQx2esz8e7UBrTIbNyG6TIeGbJdkX2oepX6cld1xsc+ZW3eD+8o3hwpaMEVpBA5AMb3W7+wONT1CyrELfZUN87Nf07y3pAVWp5X6QZe4IWRz/6WvwZKLxt+AULN/udGtj4kUdXDCbxfNlHSalxJ/aE+UjBik0TA5+uPnahnwRUm9FPqiQKBPiJ3lBeHq/Os/fIDZ4H8Wbd4CCSq7Wh4WzE8esguwnXZ1YKeiMex5acuuowzfuhhy/ZqQoXzXuWVGPjcZn2QLRrF3Sy7/pTwd4c1ls95CnYP80Qg8oxe/c+MkOlm5rP4M8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
